### ISSUE TITLE
Heavy Spam of Console Error 'CreatureSpawnEvent' Continues

### ISSUE THREAD

**Issue by EchocallingEarth** [imDaniX/dangerous-caves#4]
Error reported previously. 

The recommendation by the dev was followed and updated to current build/release

Upon downloading the newest release the error/issue persists. The previous request was closed as solved. Assuming this requires a new issue to be opened.

Details for error log:
At this time the error spams repeatedly and does not stop. Until we stopped the server and removed plugin again. The previous error repeated several times and stopped on its own.  This means some change made has caused a new issue in the recurrence of the error.

I am providing a section of our server log containing the error.
https://pastebin.com/XYksYhb6

No in-game messages or chat also no noticed lag in-game or tps drop.

My players on all 3 of our current server networks are excited to have this plugin however the error is currently preventing it. Please review and if additional information is needed to resolve, message me here or on discord EchocallingEarth#9331

My time zone is US Eastern Standard and I will do my best to respond as quickly as possible.

EchocallingEarth
(Owner Friendlyworldserve Network©)

**Comment by imDaniX** [comment]
Please recheck your version - you're using 2.0.11. The problem was fixed between 2.0.12 and 2.0.13.

**Comment by EchocallingEarth** [comment]
Okay testing now. 
Issued a new warning:
[19:46:47] [Server thread/WARN]: [DangerousCaves] Task #49 for DangerousCaves v2.0.12-9 generated an exception
java.lang.NoSuchMethodError: org.bukkit.entity.Player.getChunk()Lorg/bukkit/Chunk;
        at com.github.evillootlye.caves.caverns.CavesAging.tick(CavesAging.java:100) ~[?:?]
        at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_241]
        at com.github.evillootlye.caves.ticks.Dynamics.tick(Dynamics.java:32) ~[?:?]
        at com.github.evillootlye.caves.ticks.Dynamics.lambda$new$0(Dynamics.java:20) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-8faa8b4-7f61a25]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot.jar:git-Spigot-8faa8b4-7f61a25]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [spigot.jar:git-Spigot-8faa8b4-7f61a25]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [spigot.jar:git-Spigot-8faa8b4-7f61a25]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot.jar:git-Spigot-8faa8b4-7f61a25]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot.jar:git-Spigot-8faa8b4-7f61a25]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

**Comment by EchocallingEarth** [comment]
Other than the above warning so far no other issues. And the warning may possibly be fixed in 2.0.13 However as I stated above I am not finding that release.  and will test again as soon as I have the link.

**Comment by imDaniX** [comment]
Latest builds are available in "[Actions](https://github.com/imDaniX/dangerous-caves/actions)" tab - you can download archive(artifact) with plugin itself and a conifg.
I don't want to update SpigotMC resource page too frequently, that's why you can't find every update there.

**Comment by EchocallingEarth** [comment]
Thanks, I grab that and update and test again before we consider the warning anything to be concerned with.

**Comment by EchocallingEarth** [comment]
Okay so for whatever reason it keeps looping me and I have been unsuccessful in locating the .jar for 2.0.13. If you can send me a direct link I'd be very grateful. Thanks

**Comment by imDaniX** [comment]
It's better to download [latest build](https://github.com/imDaniX/dangerous-caves/actions/runs/60524615).

**Comment by EchocallingEarth** [comment]
Awesome and thanks. tested and no warnings or errors. That fixed it all. Recommend updating Spigit to this version 2.0.15 That way others do not report unnecessarily. As this version is running perfectly. Later today I will provide a great review.

Second thought if you are interested look into sharing your plugin on Songoda. Just an idea.

On that note, I am closing this request. If you ever need a willing player or owner to test the plugin or additions to it message me. Thanks again fr your attention to this and quick fix.

**Comment by imDaniX** [comment]
Thank you for the report and testing. I was going to update SpigotMC page after solving this issue, so, here I go.
